language: objective-c
osx_image: xcode10.2
env:
  - DESTINATION="OS=12.2,name=iPhone X" SCHEME="Ecno" SDK=iphonesimulator12.2
before_install:
  - gem install xcpretty --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild test -project Ecno.xcodeproj -scheme $SCHEME -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild test -project Example.xcodeproj -scheme "Example" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c
